#!/bin/bash

# validFloat -- Tests whether a number is a valid floating-point value.
#   Note that this script can't accept scientific (1.304e5) notation.

# To test whether an entered value is a valid floating-point number,
#   we need to split the value into two parts: the integer portion
#   and the fractional portion. We test the first part to see whether
#   it's a valid integer, and then we test whether the second part is a
#   valid >=0 integer. So -30.5 evaluates as valid, but -30.-8 doesn't.

# To include another shell script as part of this one, use the "." source
#   notation. Easy enough.

. validint

validFloat()
{
  fvalue="$1"
}
